import os

defaults = {
    'aps_cube': 1,
    'qc_plots': 1,
    'pyp_params': 1,
    'spec_fit': 1,
    'table_creator': 1,
    'nproc': 1,
    'aps_flag': 1,
    'sky_plot_flag': 1,
    'target_snr': 20,
    'levels': [5, 30],
    'blue_wav': 5100,
    'red_wav': 6450,
    'aps_wav': 6450,
    'cov_flag': 0,
    'redshift': 0,
    'blue_fit_flag': 0,
    'red_fit_flag': 0,
    'aps_fit_flag': 1,
    'vel_range': 500,
    'disp_max': 400,
    'line_flux': 1000,
    'line_vel': 0,
    'aps_lam_min': 3600,
    'aps_lam_max': 8750,
    'blue_lam_min': 3600,
    'blue_lam_max': 5475,
    'red_lam_min': 5800,
    'red_lam_max': 9400,
    'vorbin_flag': 1,
    'resol_flag': 0,
    'fwhm_blue': 2.1,
    'fwhm_red': 2.6,
    'fwhm_aps': 2.3,
    'el_flag': 1,
    'boot_flag': 1,
    'sigmaclip_flag': 0,
    'sigmaclip_limit': 30,
}

# python_exe = 'python3'

